#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
n=0
while (( n++ < 20 )); do
	case $n in
		4)
			echo "$n"
			echo "bad luck from China"
			;;
		9)
			echo "$n"
			echo "bad luck from Japan"
			;;
		17)
			echo "$n"
			echo "bad luck from Italy"
			;;
		*)
			echo "$n"
			;;
	esac
done
